#!/usr/bin/env python3
# ← 互換性修正: list[str] | None 等の Python 3.10+ 構文を 3.9 以前でも動作させる
from __future__ import annotations
"""
Basetract Content Generator
raw JSONデータ（Term/Definition ペアリスト）から問題形式のデータを生成する。
"""

import json
import uuid
import random
import os
import logging
import argparse

# 中央化インポートマネージャーを使用
from import_manager import setup_tools_import, import_profile_loader
setup_tools_import()
profile_loader = import_profile_loader()


def generate_id(prefix: str = "GEN") -> str:
    """UUIDベースのIDを生成する。"""
    return f"{prefix}-{uuid.uuid4().hex[:8].upper()}"


class ContentGenerator:
    """
    用語と定義のペアから、システム標準フォーマットの問題データを生成する。
    """

    def __init__(self, source_path: str, category: str = "Autogenerated",
                 id_prefix: str = "GEN", output_format: str = "js"):
        self.source_path = source_path
        self.category = category
        self.id_prefix = id_prefix
        self.output_format = output_format  # "js" or "json"

    def run(self, output_path: str | None = None) -> list[dict]:
        logger.info(f"Generating content from: {self.source_path}")

        try:
            with open(self.source_path, 'r', encoding='utf-8') as f:
                raw_data = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError) as e:
            logger.error(f"Source error: {e}")
            return []

        if not isinstance(raw_data, list) or len(raw_data) < 4:
            logger.error("At least 4 entries required for distracted generation.")
            return []

        segments = []
        for entry in raw_data:
            if not isinstance(entry, list) or len(entry) < 2:
                continue
            term = str(entry[0]).strip()
            definition = str(entry[1]).strip()
            if not term or not definition:
                continue

            segment = self._build_segment(term, definition, raw_data)
            segments.append(segment)

        if output_path is None:
            base = os.path.splitext(self.source_path)[0]
            ext = 'js' if self.output_format == 'js' else 'json'
            output_path = f"{base}_gen.{ext}"

        self._save(segments, output_path)
        return segments

    def _build_segment(self, term: str, definition: str, all_data: list) -> dict:
        """問題項目を構築する。"""
        options, answer = self._generate_options(definition, all_data)
        
        # 誠実な構造: 固定の「定型文」による装飾を排除し、事実のみを提供
        return {
            "id": generate_id(self.id_prefix),
            "category": self.category,
            "text": f"次の定義に最も適合する用語を選択してください:\n「{definition}」",
            "type": "choice",
            "answer": answer,
            "options": options,
            "logic": (
                f"【正解の根拠】'{term}' の定義: {definition} "
                f"【誤答の根拠】他の選択肢は本用語と定義が異なる別の技術概念を指すため誤り。"
                f"【学習ポイント】'{term}' とその定義を混同しないよう、具体的な使用文脈とともに記憶すること。"
                f"教科書の該当セクションを参照し、関連する数値・コマンド・プロトコル名も確認すること。"
            ),
            "plan": f"用語 '{term}' の定義と周辺概念を確認してください。",
            "weight": 0.1,
            "textbook_ref": [self.category],
            "tags": ["auto-generated"],
            "difficulty": "Medium"
        }

    def _generate_options(self, correct: str, all_data: list) -> tuple[list[str], str]:
        """正解＋3つのディストラクターから選択肢リストを生成する。"""
        pool = list(set(
            str(d[1]).strip()
            for d in all_data
            if isinstance(d, list) and len(d) >= 2 and str(d[1]).strip() != correct
        ))

        sample_size = min(len(pool), 3)
        if sample_size < 3:
            logger.warning(f"Insufficient distractors ({sample_size}/3). Options may overlap.")

        distractors = random.sample(pool, sample_size)
        all_opts = [correct] + distractors
        random.shuffle(all_opts)

        final_opts = [f"{chr(65 + i)}. {opt}" for i, opt in enumerate(all_opts)]
        correct_label = f"{chr(65 + all_opts.index(correct))}. {correct}"
        return final_opts, correct_label

    def _save(self, segments: list[dict], output_path: str) -> None:
        """指定フォーマットでファイルに保存する。"""
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            if self.output_format == "js":
                f.write(f"window.dataBuffer = {json.dumps(segments, ensure_ascii=False, indent=2)};")
            else:
                json.dump(segments, f, ensure_ascii=False, indent=2)
        logger.info(f"Generated content saved: {output_path}")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')
    logger = logging.getLogger(__name__)

    parser = argparse.ArgumentParser(description="Basetract Content Generator")
    parser.add_argument("source", help="Path to input JSON file")
    parser.add_argument("--output", "-o", help="Output file path")
    parser.add_argument("--format", "-f", choices=["js", "json"], default="js", help="Output format")
    parser.add_argument("--category", "-c", default="Autogenerated", help="Category string")
    parser.add_argument("--prefix", "-p", default="GEN", help="ID prefix")
    args = parser.parse_args()

    gen = ContentGenerator(
        source_path=args.source,
        category=args.category,
        id_prefix=args.prefix,
        output_format=args.format,
    )
    gen.run(output_path=args.output)
else:
    logger = logging.getLogger(__name__)
